# Generated by Django 3.1.6 on 2021-03-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='dp',
            field=models.ImageField(default='../static/images/logo', upload_to=''),
        ),
    ]
