# Generated by Django 3.1.6 on 2021-02-26 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('team_description', models.CharField(blank=True, max_length=150, null=True)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('registration_starts', models.DateField()),
                ('registration_ends', models.DateField()),
                ('tournament_starts', models.DateField()),
                ('tournament_ends', models.DateField()),
                ('total_teams', models.IntegerField(blank=True, default=0, null=True)),
                ('banner', models.ImageField(upload_to='tournament_banners')),
                ('logo', models.ImageField(default='../static/images/logo.png', upload_to='tournament_logo')),
                ('prizepool', models.IntegerField()),
                ('game', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_email', models.EmailField(default='', max_length=254)),
                ('contact_no', models.IntegerField(blank=True, default=0, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(to='main.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='uuid4', max_length=100)),
                ('status', models.CharField(choices=[('WARMUP', 'Warm up'), ('KNIFE', 'Knife'), ('LIVE', 'Live'), ('PAUSED', 'Paused'), ('OVERTIME', 'Over time'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='WARMUP', max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('skip_veto', models.BooleanField(default=True)),
                ('team_1_score', models.IntegerField(default=0)),
                ('team_2_score', models.IntegerField(default=0)),
                ('veto_mappool', models.CharField(blank=True, max_length=500, null=True)),
                ('max_maps', models.IntegerField(default=1)),
                ('team_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_1', to='main.team')),
                ('team_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_2', to='main.team')),
                ('tournament', models.ManyToManyField(to='main.Tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='main.team')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
