# Generated by Django 3.1.6 on 2021-02-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>vs<django.db.models.fields.related.ForeignKey>', max_length=100),
        ),
    ]
