# Generated by Django 3.1.6 on 2021-02-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_match_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
    ]
