# Generated by Django 3.1.6 on 2021-03-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210321_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='tournament',
        ),
        migrations.AddField(
            model_name='tournament',
            name='servers',
            field=models.ManyToManyField(to='main.Server'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
