# Generated by Django 3.1.6 on 2021-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210322_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='player1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='player2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='player3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='player4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='player5',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
