# Generated by Django 3.1.6 on 2021-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210323_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.AddField(
            model_name='server',
            name='aws_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
