# Generated by Django 3.1.6 on 2021-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210327_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='total_teams',
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams_left',
            field=models.ManyToManyField(related_name='teams_left', to='main.Team'),
        ),
    ]
