# Generated by Django 3.1.6 on 2021-04-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210408_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
    ]
